#!/bin/sh
# -*- sh -*-
# vim: set syntax=sh
# code: language=shellscript

# Script to search for writing & formatting violations and other mistakes.
# Copyright (C) 2021  Michael Federczuk
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

if [ $# -gt 0 ]; then
	echo "$0: too many arguments: $#" >&2
	echo "usage: $0" >&2
	exit 4
fi

root_dir_path="$(dirname -- "$0")" || exit
readonly root_dir_path

readonly local_ts_node_path="$root_dir_path/node_modules/.bin/ts-node"

if [ ! -x "$local_ts_node_path" ]; then
	if ! command -v npm > '/dev/null'; then
		echo "$0: npm: program missing" >&2
		exit 27
	fi

	npm install || exit
fi

"$local_ts_node_path" "$root_dir_path/check.ts"
